- type: gameMapPool
  id: CorvaxDefaultMapPool
  maps:
  - CorvaxDelta
  - CorvaxAvrite
  - CorvaxSpectrum
  - CorvaxSilly
  - CorvaxOutpost
  - CorvaxAstra
  - CorvaxGelta
  - Aspid
  - Bagel
  - Box
  - Cluster
  - Core
  - Fland
  - Marathon
  - Meta
  - Omega
  - Origin
  - Saltern
  - Packed
  - Europa
  - Gate
  - Silly 
  - Atlas
  - Gemini
  - Reach
