{
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "Backmen.ru By Firefox",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "idcardiog"
    },
	  {
      "name": "idcardmog"
    },
    {
      "name": "black-inhand-left",
      "directions": 4
    },
    {
      "name": "black-inhand-right",
      "directions": 4
    },    
   ]
  }
