name: Test Packaging

on:
  push:
    branches: [ master ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '**.git**'
      - '**.yml'
      # no docs on which one of these is supposed to work, so
      # why not just do both
      - 'RobustToolbox'
      - 'RobustToolbox/**'
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ master ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'
      - '**.git**'
      - '**.yml'
      - 'RobustToolbox'
      - 'RobustToolbox/**'

jobs:
  build:
    if: github.actor != 'PJBot' && github.event.pull_request.draft == false
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Update submodules
        run: |
          git submodule update --init --recursive

      - name: Install dependencies
        run: dotnet restore

      - name: Package client
        run: |
          Tools/package_server_build.py -p win-x64 linux-x64 osx-x64 linux-arm64
          Tools/package_client_build.py

      - name: Update Build Info
        run: Tools/gen_build_info.py

      - name: Shuffle files around
        run: |
          mkdir "release/${{ github.sha }}"
          mv release/*.zip "release/${{ github.sha }}"
